name:
  type: string
  required: True
links:
  type: dict
  schema:
    confluence_page_url:
      type: string
    code_repository_url:
      type: string
description:
  type: string
  required: True
status:
  type: string
  required: True

